<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

use Carbon\Carbon;

class User extends \TCG\Voyager\Models\User
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getAvatarAttribute($value)
    {
        return parent::getAvatarAttribute(asset('storage').'/'.$value); // TODO: Change the autogenerated stub
    }

    public function getCreatedAtAttribute($value)
    {
        return Carbon::parse($value)->diffForHumans();
    }

    public function comments()
    {
        return $this->hasMany('App\Comment');
    }

    public function films()
    {
        return $this->hasMany('App\Film', 'author');
    }

    public function getComments()
    {
        $comments = $this->comments()->where('active', 1)->latest()->with('user')->paginate(10);
        return $comments;
    }

}
